
workflows:
  react-web-app:
    name: React Web App
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
    artifacts:
      - build/**
