
workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.npm
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: |
          npm run build
          mkdir -p dist
          # Ensure the build directory exists and has content
          ls -la dist
      - name: Set up Capacitor Android
        script: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap init "Aviator Game" app.lovable.aviator --web-dir=dist
          npx cap add android
      - name: Copy web assets to Android
        script: |
          # Make sure the dist directory exists before syncing
          if [ -d "dist" ]; then
            npx cap sync android
          else
            echo "Error: dist directory not found"
            exit 1
          fi
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
